# Generated by Django 3.2.4 on 2021-06-11 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Queens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('winner', models.BooleanField()),
                ('missCongeniality', models.BooleanField()),
                ('quote', models.TextField()),
                ('image_url', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='My_Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('O', 'Open'), ('C', 'Closed'), ('G', 'Give')], default='C', max_length=50)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
                ('queen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading_outpost.queens')),
            ],
        ),
    ]
